# Generated by Django 4.0.6 on 2022-08-05 11:07

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id_document', models.FileField(null=True, upload_to='user/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('number', models.BigIntegerField(default=1659697639, primary_key=True, serialize=False)),
                ('area_a', models.PositiveIntegerField()),
                ('area_ca', models.PositiveIntegerField()),
                ('quality', models.IntegerField(choices=[(1, 'majeur(s) non interdit(s) jouissant de ces droits civils'), (2, 'mineur émancipé'), (3, 'mandataire'), (4, 'copropriétaire'), (5, 'administrateur des bien de la communauté'), (6, 'représentant légal'), (7, 'suivant jugement du'), (8, 'suivant contrat'), (9, "pourvu d'un conseil judiciaire en la personne de")], default=1)),
                ('type', models.IntegerField(choices=[(1, 'rural non bâti'), (2, 'rural bâti'), (3, 'urbain non bâti'), (4, 'urbain bâti')])),
                ('info', models.CharField(max_length=100)),
                ('quarter', models.CharField(max_length=100)),
                ('real_name', models.CharField(max_length=100)),
                ('prefecture', models.CharField(max_length=100)),
                ('east', models.CharField(max_length=100)),
                ('western', models.CharField(max_length=100)),
                ('north', models.CharField(max_length=100)),
                ('south', models.CharField(max_length=100)),
                ('nif', models.FileField(upload_to='requisition/req-<django.db.models.fields.BigIntegerField>')),
                ('liquidation_receipt', models.FileField(blank=True, null=True, upload_to='requisition/req-<django.db.models.fields.BigIntegerField>')),
                ('land_receipt', models.FileField(upload_to='requisition/req-<django.db.models.fields.BigIntegerField>')),
                ('authorization', models.FileField(blank=True, null=True, upload_to='requisition/req-<django.db.models.fields.BigIntegerField>')),
                ('floor_plan', models.FileField(upload_to='requisition/req-<django.db.models.fields.BigIntegerField>')),
                ('notarial_instrument', models.FileField(blank=True, null=True, upload_to='requisition/req-<django.db.models.fields.BigIntegerField>')),
                ('pay', models.CharField(blank=True, default='2022-08-05 11:07:19.027063', max_length=30, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pay_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('co_owner', models.ManyToManyField(blank=True, related_name='owners', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, choices=[('A', 'En cours'), ('P', 'En attente'), ('C', 'Rejetée')], max_length=1, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.requisition')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('F', 'Mme'), ('M', 'M.')], max_length=1)),
                ('marital_status', models.CharField(choices=[('1', 'Célibataire'), ('2', 'époux'), ('3', 'veuf')], default='1', max_length=1)),
                ('partner_name', models.CharField(blank=True, max_length=200)),
                ('profession', models.CharField(max_length=100, null=True)),
                ('nationality', models.CharField(default='togolaise', max_length=50)),
                ('birthday', models.DateField(default=django.utils.timezone.now, verbose_name='birthday')),
                ('bornAt', models.CharField(max_length=100)),
                ('address', models.CharField(default='', max_length=200)),
                ('residence', models.CharField(blank=True, default=models.CharField(default='', max_length=200), max_length=200)),
                ('type', models.CharField(blank=True, choices=[('CLIENT', 'Requérant'), ('GUICHET', 'Agent Division cadastre'), ('BORNAGE', 'Agent bureau de bornage'), ('GEOMETRE', 'Géomètre'), ('DESSIN', 'Dessinateur'), ('CONSERVATION', 'Conservateur')], default='CLIENT', max_length=100)),
                ('phone', models.CharField(max_length=12, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=1000)),
                ('proof_file', models.FileField(upload_to='requisition/req-')),
                ('state', models.BooleanField(null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('state_date', models.DateTimeField(blank=True, null=True)),
                ('requisition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.requisition')),
            ],
        ),
    ]
