# Generated by Django 4.0.6 on 2022-08-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_complaint_author_complaint_state_author_state_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='raison',
            field=models.CharField(default='Phase initiale', max_length=100),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='number',
            field=models.BigIntegerField(default=1659814460, primary_key=True, serialize=False),
        ),
    ]
