# Generated by Django 4.0.6 on 2022-08-12 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_complaint_id_alter_requisition_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='id',
            field=models.BigIntegerField(default=1660293126, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='type',
            field=models.CharField(blank=True, choices=[('CLIENT', 'Requérant'), ('GUICHET', 'Agent Division cadastre'), ('BORNAGE', 'Agent bureau de bornage'), ('GEOMETRE', 'Géometre'), ('DESSIN', 'Dessinateur'), ('CONSERVATION', 'Conservateur')], default='CLIENT', max_length=100),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='number',
            field=models.BigIntegerField(default=1660293126, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Demarcation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choosed_date', models.DateTimeField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demarcation_author', to=settings.AUTH_USER_MODEL)),
                ('drawer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drawer', to=settings.AUTH_USER_MODEL)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.requisition')),
                ('surveyor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveyor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
