# Generated by Django 4.0.6 on 2022-08-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_complaint_id_alter_requisition_number_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='id',
            field=models.BigIntegerField(default=1660393337, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='number',
            field=models.BigIntegerField(default=1660393337, primary_key=True, serialize=False),
        ),
    ]
