# Generated by Django 4.0.6 on 2022-08-13 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_landdeed_mutation_alter_complaint_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='id',
            field=models.BigIntegerField(default=1660405054, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='landdeed',
            name='number',
            field=models.BigIntegerField(default=1660405054),
        ),
        migrations.AlterField(
            model_name='landdeed',
            name='requisition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.requisition'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='number',
            field=models.BigIntegerField(default=1660405054, primary_key=True, serialize=False),
        ),
    ]
