# Generated by Django 4.0.6 on 2022-08-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_complaint_id_alter_landdeed_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='id',
            field=models.BigIntegerField(default=1660636652, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='landdeed',
            name='number',
            field=models.BigIntegerField(default=1660636652),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='number',
            field=models.BigIntegerField(default=1660636652, primary_key=True, serialize=False),
        ),
    ]
