# Generated by Django 4.0.6 on 2022-08-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_complaint_id_alter_landdeed_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='requisition/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='id',
            field=models.BigIntegerField(default=1660636664, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='landdeed',
            name='number',
            field=models.BigIntegerField(default=1660636664),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='number',
            field=models.BigIntegerField(default=1660636664, primary_key=True, serialize=False),
        ),
    ]
