# Generated by Django 4.0.6 on 2022-08-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='requisition',
            name='number',
            field=models.BigIntegerField(default=1659700246, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='pay',
            field=models.CharField(blank=True, default='2022-08-05 11:50:46.135314', max_length=30, null=True),
        ),
    ]
