# Generated by Django 4.0.6 on 2022-08-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_state_raison_alter_requisition_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='id',
            field=models.BigIntegerField(default=1659814561, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='number',
            field=models.BigIntegerField(default=1659814561, primary_key=True, serialize=False),
        ),
    ]
