# Generated by Django 4.0.6 on 2022-08-12 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_complaint_id_alter_person_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='id',
            field=models.BigIntegerField(default=1660305520, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='number',
            field=models.BigIntegerField(default=1660305520, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pv', models.TextField(max_length=1000)),
                ('floor_plan', models.FileField(blank=True, null=True, upload_to='plans/%Y/%m/%d/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('state', models.BooleanField(null=True)),
                ('demarcation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.demarcation')),
            ],
        ),
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.report')),
            ],
        ),
    ]
