# Generated by Django 4.0.6 on 2022-08-13 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_report_updated_at_alter_complaint_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='landDeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField(default=1660403210)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mutation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('way', models.CharField(blank=True, choices=[('H', 'Héritage'), ('S', 'Vente')], default='H', max_length=1)),
                ('landDeed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.landdeed')),
                ('to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='complaint',
            name='id',
            field=models.BigIntegerField(default=1660403210, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='number',
            field=models.BigIntegerField(default=1660403210, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='state',
            name='state',
            field=models.CharField(blank=True, choices=[('A', 'En cours'), ('P', 'En attente'), ('C', 'Rejetée'), ('T', 'Terminée')], max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('landDeed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.landdeed')),
                ('purchase', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.mutation')),
            ],
        ),
        migrations.AddField(
            model_name='landdeed',
            name='requisition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.requisition'),
        ),
    ]
