# Generated by Django 4.0.6 on 2022-08-22 08:41

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_complaint_id_alter_landdeed_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='id',
            field=models.BigIntegerField(default=1661157701, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='landdeed',
            name='number',
            field=models.BigIntegerField(default=1661157701),
        ),
        migrations.AlterField(
            model_name='person',
            name='residence',
            field=models.CharField(blank=True, default=django.db.models.fields.Field.value_from_object, max_length=200),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='number',
            field=models.BigIntegerField(default=1661157701, primary_key=True, serialize=False),
        ),
    ]
